language: java

branches:
  only:
    - 3.9-on-v4-codebase

services:
  - docker

install: true

jdk:
  - openjdk11

env:
  - PROJECT=chapter1
  - PROJECT=chapter2
  - PROJECT=chapter3
  - PROJECT=chapter4
  - PROJECT=chapter5
  - PROJECT=chapter6
  - PROJECT=chapter13
  - PROJECT=part2-steps-challenge

script:
  - cd $PROJECT
  - ./gradlew build --console=plain --refresh-dependencies

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email:
    - julien.ponge@gmail.com
    - julien@julienviet.com
