language: java

branches:
  only:
    - 3.9-on-v4-codebase

services:
  - docker

install: true

matrix:
  include:
    - jdk: openjdk11

script:
  - ./gradlew build-chapters --refresh-dependencies
  - ./gradlew build-part2-steps-challenge --refresh-dependencies

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
