apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: heat-sensor-service
  name: heat-sensor-service
spec:
  selector:
    matchLabels:
      app: heat-sensor-service
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: heat-sensor-service
    spec:
      containers:
        - image: vertx-in-action/heat-sensor-service:latest
          name: heat-sensor-service
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5

